name: Build

on:
  push:
    tags: "*"
  workflow_dispatch:

jobs:
  github_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        run: |
          flutter pub get
          flutter build web --wasm --base-href "/$(echo ${{ github.repository }} | sed -e 's#.*/##')/"

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh release view -R ${{ github.repository }} '${{ github.ref_name }}'; then
            gh release create -R ${{ github.repository }} '${{ github.ref_name }}' -d -t '${{ github.ref_name }}' -n 'The purpose of this project is to evaluate the pair-programming; **NOT FOR A PRACTICAL USE.**

          - The Windows release requires the latest [Visual C++ redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
          - The Linux release may require some additional dependencies; identify them with the `ldd` command
          - For Android devices, download the `.apk` file and install it with "Allow installation of apps from unknown sources" enabled (the `.aab` release is experimental)
          - For web, visit the [deployment](https://watamario15.github.io/formsclient/) or the [`gh-pages` branch](https://github.com/watamario15/formsclient/tree/gh-pages)
          - The macOS and the iOS release are experimental and not notarized (not tested at all)'
          fi

  windows:
    name: Windows Release
    needs: [create_release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        run: |
          flutter pub get
          flutter build windows

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          compress-archive build/windows/x64/runner/Release/ 'windows-${{ github.ref_name }}.zip'
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './windows-${{ github.ref_name }}.zip' --clobber

  windows-arm64:
    name: Windows ARM64 Release
    needs: [create_release]
    runs-on: windows-11-vs2026-arm
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          cache: true

      - name: Build
        run: |
          flutter pub get
          flutter build windows

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          compress-archive build/windows/arm64/runner/Release/ 'windows-${{ github.ref_name }}-arm64.zip'
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './windows-${{ github.ref_name }}-arm64.zip' --clobber

  macos:
    name: macOS Release
    needs: [create_release]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        run: |
          flutter pub get
          flutter build macos

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/macos/Build/Products/Release
          7z a -tzip -y 'macos-${{ github.ref_name }}.app.zip' "$(echo ${{ github.repository }} | sed -e 's#.*/##').app"
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './macos-${{ github.ref_name }}.app.zip' --clobber

  linux:
    name: Linux Release
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        run: |
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter pub get
          flutter build linux

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/linux/x64/release
          tar -zcvf linux-${{ github.ref_name }}.tar.gz bundle
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './linux-${{ github.ref_name }}.tar.gz' --clobber

  linux-arm64:
    name: Linux AArch64 Release
    needs: [create_release]
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          cache: true

      - name: Build
        run: |
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter pub get
          flutter build linux

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/linux/arm64/release
          tar -zcvf linux-${{ github.ref_name }}-arm64.tar.gz bundle
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './linux-${{ github.ref_name }}-arm64.tar.gz' --clobber

  android:
    name: Android Release
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: "25"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        run: |
          flutter pub get
          flutter build apk
          flutter build appbundle

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv build/app/outputs/flutter-apk/{app-release,'android-${{ github.ref_name }}'}.apk
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './build/app/outputs/flutter-apk/android-${{ github.ref_name }}.apk' --clobber
          mv build/app/outputs/bundle/release/{app-release,'android-${{ github.ref_name }}'}.aab
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './build/app/outputs/bundle/release/android-${{ github.ref_name }}.aab' --clobber

  ios:
    name: iOS/iPadOS Release
    needs: [create_release]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        run: |
          flutter build ios --no-codesign
          flutter pub get

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/ios/iphoneos
          7z a -tzip -y 'ios-${{ github.ref_name }}.app.zip' Runner.app
          gh release upload -R ${{ github.repository }} '${{ github.ref_name }}' './ios-${{ github.ref_name }}.app.zip' --clobber
